/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Compare */
        post: operations["compare_compare_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/field/accurate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Accurate Field */
        post: operations["submit_accurate_field_field_accurate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/score": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Score */
        post: operations["submit_score_score_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/study": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Study */
        post: operations["submit_study_study_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sweep": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Sweep */
        post: operations["submit_sweep_sweep_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/validation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Validation */
        get: operations["get_validation_validation_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActivationCurve
         * @description One cell's response across the sweep's amplitude grid, aligned index-for-index
         *     with ``AmplitudeSweepResponse.amplitudes_uA``.
         *
         *     Note there is deliberately no "activation fraction" here. The patch is a target
         *     plus its bystanders — a handful of cells — so a fraction would be a two- or
         *     three-level step function wearing the costume of a sigmoid. Per-cell traces are
         *     what the engine actually knows.
         */
        ActivationCurve: {
            /** Activated */
            activated: boolean[];
            /**
             * Blocks
             * @default false
             */
            blocks: boolean;
            /** Cell Id */
            cell_id: string;
            /** Crossing Ua */
            crossing_uA?: number | null;
            /** Initiation Region */
            initiation_region: (string | null)[];
            /** Is Target */
            is_target: boolean;
        };
        /** AmplitudeSweepResponse */
        AmplitudeSweepResponse: {
            /** Amplitudes Ua */
            amplitudes_uA: number[];
            /** Curves */
            curves: components["schemas"]["ActivationCurve"][];
        };
        /**
         * CellMarker
         * @description A soma position on the field plane; the target is drawn filled.
         */
        CellMarker: {
            /** Is Target */
            is_target: boolean;
            /** X Um */
            x_um: number;
            /** Y Um */
            y_um: number;
        };
        /**
         * CompareResponse
         * @description One configuration scored for the Compare screen: the field and its scene
         *     overlays always, the scorecard only when requested (it costs a threshold
         *     search). This is the field-view data contract — grid + electrode outlines +
         *     soma overlays (master plan §16).
         */
        CompareResponse: {
            /** Cells */
            cells: components["schemas"]["CellMarker"][];
            /** Electrodes */
            electrodes: components["schemas"]["ElectrodeMarker"][];
            field: components["schemas"]["FieldGridResponse"];
            scorecard?: components["schemas"]["ScorecardResponse"] | null;
        };
        /**
         * ElectrodeMarker
         * @description An electrode's footprint on the field plane, for the overlay.
         */
        ElectrodeMarker: {
            /** Radius Um */
            radius_um: number;
            /** X Um */
            x_um: number;
            /** Y Um */
            y_um: number;
        };
        /**
         * FieldGridResponse
         * @description Ve (mV) on a square grid at the cell plane — the analytical field preview.
         */
        FieldGridResponse: {
            /** Ve Mv */
            ve_mV: number[][];
            /** Vmax Mv */
            vmax_mV: number;
            /** Xs Um */
            xs_um: number[];
            /** Ys Um */
            ys_um: number[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * JobStatus
         * @description A background job's state, polled by the client. When ``status`` is ``"done"``,
         *     the matching result is present — ``scorecard`` for a score job, ``field`` (+
         *     ``max_divergence_pct`` vs the analytical preview) for an accurate-field job.
         *     ``cached`` means it was served from a prior identical run (P7 S3).
         */
        JobStatus: {
            /**
             * Cached
             * @default false
             */
            cached: boolean;
            /** Error */
            error?: string | null;
            field?: components["schemas"]["FieldGridResponse"] | null;
            /** Fraction */
            fraction: number;
            /** Id */
            id: string;
            /** Max Divergence Pct */
            max_divergence_pct?: number | null;
            /** Message */
            message: string;
            scorecard?: components["schemas"]["ScorecardResponse"] | null;
            /**
             * Status
             * @enum {string}
             */
            status: "running" | "done" | "error";
            study?: components["schemas"]["StudyResult"] | null;
            sweep?: components["schemas"]["AmplitudeSweepResponse"] | null;
        };
        /**
         * SceneControls
         * @description The Compare screen's inputs — the same handful of controls the Dash app
         *     exposes, translated to specs server-side via ``app.scene.build_scene``.
         */
        SceneControls: {
            /**
             * Electrode Um
             * @default 10
             */
            electrode_um: number;
            /**
             * Extent Um
             * @default 130
             */
            extent_um: number;
            /**
             * Include Scorecard
             * @default false
             */
            include_scorecard: boolean;
            /**
             * Layout
             * @default single
             * @enum {string}
             */
            layout: "single" | "bipolar";
            /**
             * N
             * @default 61
             */
            n: number;
            /**
             * Neighbor Um
             * @default 40
             */
            neighbor_um: number;
            /**
             * Phase Width Us
             * @default 200
             */
            phase_width_us: number;
            /**
             * Pitch Um
             * @default 60
             */
            pitch_um: number;
            /**
             * Sigma S Per M
             * @default 1
             */
            sigma_S_per_m: number;
        };
        /**
         * ScorecardResponse
         * @description The evaluator's operating-window verdict. ``activated=False`` means the
         *     target never fired in the searched range and every other field is absent.
         */
        ScorecardResponse: {
            /** Activated */
            activated: boolean;
            /** Limiting */
            limiting?: string | null;
            /** Limiting Off Id */
            limiting_off_id?: string | null;
            /** Off Min Ua */
            off_min_uA?: number | null;
            /** Off Target Thresholds Ua */
            off_target_thresholds_uA?: {
                [key: string]: number;
            } | null;
            /** Offtarget Hash */
            offtarget_hash?: string | null;
            /** Ratio */
            ratio?: number | null;
            /** Safe At Target */
            safe_at_target?: boolean | null;
            /** Safety Ceiling Ua */
            safety_ceiling_uA?: number | null;
            /** Target Ua */
            target_uA?: number | null;
            /** Usable */
            usable?: boolean | null;
            /** Usable Margin Ua */
            usable_margin_uA?: number | null;
            /** Window Hi Ua */
            window_hi_uA?: number | null;
            /** Window Lo Ua */
            window_lo_uA?: number | null;
        };
        /**
         * StudyControls
         * @description A geometry sweep: the diameter × pitch grid to explore, plus the patch it is
         *     scored on. Combos with ``pitch < diameter`` (which would overlap) are dropped.
         */
        StudyControls: {
            /**
             * Aperture Um
             * @default 120
             */
            aperture_um: number;
            /**
             * Arrangement
             * @default hex
             * @enum {string}
             */
            arrangement: "grid" | "hex";
            /** Diameters Um */
            diameters_um?: number[];
            /**
             * Neighbor Um
             * @default 40
             */
            neighbor_um: number;
            /**
             * Phase Width Us
             * @default 200
             */
            phase_width_us: number;
            /** Pitches Um */
            pitches_um?: number[];
            /**
             * Sigma S Per M
             * @default 1
             */
            sigma_S_per_m: number;
            /**
             * Trajectory Jitter Deg
             * @default 15
             */
            trajectory_jitter_deg: number;
            /**
             * Trajectory K
             * @default 1
             */
            trajectory_k: number;
        };
        /**
         * StudyPoint
         * @description One evaluated geometry on the selectivity-versus-cost plane.
         */
        StudyPoint: {
            /** Cost Ua */
            cost_uA: number;
            /** Diameter Um */
            diameter_um: number;
            /** On Frontier */
            on_frontier: boolean;
            /** Pitch Um */
            pitch_um: number;
            /** Safe */
            safe: boolean;
            /** Selectivity Ua */
            selectivity_uA: number;
            /** Spread Ua */
            spread_uA?: number | null;
        };
        /**
         * StudyResult
         * @description A completed sweep: every activated geometry, and how many were swept.
         */
        StudyResult: {
            /** N Geometries */
            n_geometries: number;
            /** Points */
            points: components["schemas"]["StudyPoint"][];
        };
        /**
         * SweepControls
         * @description An amplitude sweep of the scene: who fires, at what current.
         */
        SweepControls: {
            /**
             * Amp Max Ua
             * @default 200
             */
            amp_max_uA: number;
            /**
             * Amp Min Ua
             * @default 1
             */
            amp_min_uA: number;
            /**
             * Electrode Um
             * @default 10
             */
            electrode_um: number;
            /**
             * Extent Um
             * @default 130
             */
            extent_um: number;
            /**
             * Include Scorecard
             * @default false
             */
            include_scorecard: boolean;
            /**
             * Layout
             * @default single
             * @enum {string}
             */
            layout: "single" | "bipolar";
            /**
             * N
             * @default 61
             */
            n: number;
            /**
             * N Amplitudes
             * @default 24
             */
            n_amplitudes: number;
            /**
             * Neighbor Um
             * @default 40
             */
            neighbor_um: number;
            /**
             * Phase Width Us
             * @default 200
             */
            phase_width_us: number;
            /**
             * Pitch Um
             * @default 60
             */
            pitch_um: number;
            /**
             * Sigma S Per M
             * @default 1
             */
            sigma_S_per_m: number;
            /**
             * Spacing
             * @default linear
             * @enum {string}
             */
            spacing: "linear" | "log";
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * ValidationReport
         * @description The trust panel: which reproductions currently pass (master plan §15). This is
         *     the committed report CI regenerates — the app renders it, never recomputes it.
         */
        ValidationReport: {
            /** N Pass */
            n_pass: number;
            /** N Total */
            n_total: number;
            /** Reproductions */
            reproductions: components["schemas"]["ValidationReproduction"][];
        };
        /**
         * ValidationReproduction
         * @description One published/physics check the engine reproduces, and how it was measured.
         */
        ValidationReproduction: {
            /** Criterion */
            criterion: string;
            /** Measured */
            measured: string;
            /** Name */
            name: string;
            /**
             * Note
             * @default
             */
            note: string;
            /** Passed */
            passed: boolean;
            /** Source */
            source: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    compare_compare_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SceneControls"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompareResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_accurate_field_field_accurate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SceneControls"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    get_job_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_score_score_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SceneControls"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_study_study_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StudyControls"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_sweep_sweep_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SweepControls"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_validation_validation_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationReport"];
                };
            };
        };
    };
}
