/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Compare */
        post: operations["compare_compare_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * CellMarker
         * @description A soma position on the field plane; the target is drawn filled.
         */
        CellMarker: {
            /** Is Target */
            is_target: boolean;
            /** X Um */
            x_um: number;
            /** Y Um */
            y_um: number;
        };
        /**
         * CompareResponse
         * @description One configuration scored for the Compare screen: the field and its scene
         *     overlays always, the scorecard only when requested (it costs a threshold
         *     search). This is the field-view data contract — grid + electrode outlines +
         *     soma overlays (master plan §16).
         */
        CompareResponse: {
            /** Cells */
            cells: components["schemas"]["CellMarker"][];
            /** Electrodes */
            electrodes: components["schemas"]["ElectrodeMarker"][];
            field: components["schemas"]["FieldGridResponse"];
            scorecard?: components["schemas"]["ScorecardResponse"] | null;
        };
        /**
         * ElectrodeMarker
         * @description An electrode's footprint on the field plane, for the overlay.
         */
        ElectrodeMarker: {
            /** Radius Um */
            radius_um: number;
            /** X Um */
            x_um: number;
            /** Y Um */
            y_um: number;
        };
        /**
         * FieldGridResponse
         * @description Ve (mV) on a square grid at the cell plane — the analytical field preview.
         */
        FieldGridResponse: {
            /** Ve Mv */
            ve_mV: number[][];
            /** Vmax Mv */
            vmax_mV: number;
            /** Xs Um */
            xs_um: number[];
            /** Ys Um */
            ys_um: number[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * SceneControls
         * @description The Compare screen's inputs — the same handful of controls the Dash app
         *     exposes, translated to specs server-side via ``app.scene.build_scene``.
         */
        SceneControls: {
            /**
             * Electrode Um
             * @default 10
             */
            electrode_um: number;
            /**
             * Extent Um
             * @default 130
             */
            extent_um: number;
            /**
             * Include Scorecard
             * @default false
             */
            include_scorecard: boolean;
            /**
             * Layout
             * @default single
             * @enum {string}
             */
            layout: "single" | "bipolar";
            /**
             * N
             * @default 61
             */
            n: number;
            /**
             * Neighbor Um
             * @default 40
             */
            neighbor_um: number;
            /**
             * Phase Width Us
             * @default 200
             */
            phase_width_us: number;
            /**
             * Pitch Um
             * @default 60
             */
            pitch_um: number;
            /**
             * Sigma S Per M
             * @default 1
             */
            sigma_S_per_m: number;
        };
        /**
         * ScorecardResponse
         * @description The evaluator's operating-window verdict. ``activated=False`` means the
         *     target never fired in the searched range and every other field is absent.
         */
        ScorecardResponse: {
            /** Activated */
            activated: boolean;
            /** Limiting */
            limiting?: string | null;
            /** Off Min Ua */
            off_min_uA?: number | null;
            /** Ratio */
            ratio?: number | null;
            /** Safe At Target */
            safe_at_target?: boolean | null;
            /** Safety Ceiling Ua */
            safety_ceiling_uA?: number | null;
            /** Target Ua */
            target_uA?: number | null;
            /** Usable */
            usable?: boolean | null;
            /** Usable Margin Ua */
            usable_margin_uA?: number | null;
            /** Window Hi Ua */
            window_hi_uA?: number | null;
            /** Window Lo Ua */
            window_lo_uA?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    compare_compare_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SceneControls"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompareResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
